### ISSUE TITLE
draa + sclip/mclip raises an error

### ISSUE THREAD

**Issue by emotion3459** [Jaded-Encoding-Thaumaturgy/vs-aa#39]
Mismatched formats

**Comment by LightArrowsEXE** [comment]
Can't repro with regular usage. The following returns a clip just fine for me:

```py
aa = Eedi3(mclip=src, sclip_aa=True).draa(src)
```

However, this does appear to break in based_aa (which was where this was found, apparently).

```diff
- aa = Eedi3(mclip=mclip, sclip_aa=True).aa(ss, **eedi3_kwargs | kwargs)
+ aa = Eedi3(mclip=mclip, sclip_aa=True).draa(ss, **eedi3_kwargs | kwargs)
```

With some additional stacktrace helpers:

```py
01. _run_module_as_main - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:198
02. _run_code - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:88
03. <module> - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py:39
04. main - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py:430
05. run_module - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py:317
06. _run_module_as_main - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py:238
07. _run_code - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py:124
08. <module> - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\__main__.py:5
09. main - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\init.py:172
10. load_script - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\main\window.py:379
11. result - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:160
12. run - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:153
13. inline_runner - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:93
14. _run_inline - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:135
15. _execute - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:219
16. run_path - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:287
17. _run_module_code - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:98
18. _monkey_runpy_func - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\core\vsenv.py:44
19. _run_code - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:88
20. <module> - C:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\test.py:7
21. based_aa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\funcs.py:443
22. _wrapper - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\stgpytools\types\utils.py:180
23. draa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py:312
24. _aa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py:244
25. _aa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py:229
26. interpolate - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\antialiasers\eedi3.py:102
VideoNode
	Format: Gray16
	Width: 1536
	Height: 1152
	Num Frames: 2172
	FPS: 24000/1001
 VideoNode
	Format: Gray16
	Width: 1536
	Height: 1152
	Num Frames: 2172
	FPS: 24000/1001
 VideoNode
	Format: Gray16
	Width: 1536
	Height: 1152
	Num Frames: 2172
	FPS: 24000/1001
01. _run_module_as_main - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:198
02. _run_code - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:88
03. <module> - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py:39
04. main - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py:430
05. run_module - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py:317
06. _run_module_as_main - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py:238
07. _run_code - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py:124
08. <module> - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\__main__.py:5
09. main - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\init.py:172
10. load_script - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\main\window.py:379
11. result - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:160
12. run - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:153
13. inline_runner - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:93
14. _run_inline - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:135
15. _execute - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:219
16. run_path - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:287
17. _run_module_code - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:98
18. _monkey_runpy_func - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\core\vsenv.py:44
19. _run_code - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:88
20. <module> - C:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\test.py:7
21. based_aa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\funcs.py:443
22. _wrapper - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\stgpytools\types\utils.py:180
23. draa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py:312
24. _aa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py:244
25. _aa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py:229
26. interpolate - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\antialiasers\eedi3.py:102
VideoNode
	Format: Gray16
	Width: 1152
	Height: 1536
	Num Frames: 2172
	FPS: 24000/1001
 VideoNode
	Format: Gray16
	Width: 1152
	Height: 1536
	Num Frames: 2172
	FPS: 24000/1001
 VideoNode
	Format: Gray16
	Width: 1152
	Height: 1536
	Num Frames: 2172
	FPS: 24000/1001
01. _run_module_as_main - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:198
02. _run_code - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:88
03. <module> - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py:39
04. main - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py:430
05. run_module - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py:317
06. _run_module_as_main - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py:238
07. _run_code - c:\Users\light\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py:124
08. <module> - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\__main__.py:5
09. main - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\init.py:172
10. load_script - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\main\window.py:379
11. result - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:160
12. run - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:153
13. inline_runner - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:93
14. _run_inline - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:135
15. _execute - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py:219
16. run_path - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:287
17. _run_module_code - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:98
18. _monkey_runpy_func - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\core\vsenv.py:44
19. _run_code - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py:88
20. <module> - C:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\test.py:7
21. based_aa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\funcs.py:443
22. _wrapper - c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\stgpytools\types\utils.py:180
23. draa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py:312
24. _aa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py:246
25. _aa - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py:229
26. interpolate - c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\antialiasers\eedi3.py:102
VideoNode
	Format: Gray16
	Width: 1536
	Height: 1152
	Num Frames: 2172
	FPS: 24000/1001
 VideoNode
	Format: Gray16
	Width: 1536
	Height: 1152
	Num Frames: 2172
	FPS: 24000/1001
 VideoNode
	Format: Gray16
	Width: 1536
	Height: 1152
	Num Frames: 2172
	FPS: 24000/1001
2024-10-01 01:07:18.696: root: ERROR: Traceback (most recent call last):
  File "c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsengine\vpy.py", line 219, in _execute
    runpy.run_path(str(script), module.__dict__, module.__name__)
  File "c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 287, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 98, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\vspreview\core\vsenv.py", line 44, in _monkey_runpy_func
    glob_dict = orig_runpy_run_code(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\test.py", line 7, in <module>
    aa = based_aa(src)
         ^^^^^^^^^^^^^
  File "c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\funcs.py", line 443, in based_aa
    aa = Eedi3(mclip=mclip, sclip_aa=True).draa(ss, **eedi3_kwargs | kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\light\AppData\Local\Programs\Python\Python312\Lib\site-packages\stgpytools\types\utils.py", line 180, in _wrapper
    return self.function(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py", line 312, in draa
    return DoubleRater._aa(self, clip, y, x, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py", line 246, in _aa
    aa1 = super()._aa(clip, y, x, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\abstract.py", line 229, in _aa
    upscaled = self.interpolate(upscaled, False, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\light\GitHub\Jaded-Encoding-Thaumaturgy\vs-aa\vsaa\antialiasers\eedi3.py", line 107, in interpolate
    interpolated = function(  # type: ignore[operator]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\cython\\vapoursynth.pyx", line 3123, in vapoursynth.Function.__call__
vapoursynth.Error: EEDI3: sclip's format doesn't match
```

I've tried a number of things, and can't determine why this error is thrown from our side.
